---
- hosts: arvados_master
  remote_user: ubuntu
  become: true
  roles:
    - arvados_repo
#    - letsencrypt
    - arvados_master
#    - arvados_api
#    - arvados_controller
#    - git
#    - websockets
#    - container_dispatcher
