---
# file: site.yml
- import_playbook: arvados_master.yml
- import_playbook: sso.yml
- import_playbook: workbench.yml
- import_playbook: keepstore.yml
- import_playbook: worker.yml
- import_playbook: shell.yml
